workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      vars:
        XCODE_WORKSPACE: "HoS.xcworkspace"
        XCODE_SCHEME: "HoS"
      xcode: latest
    scripts:
      - name: Build unsigned iOS app
        script: |
          xcodebuild 
            -workspace "" 
            -scheme "" 
            -sdk iphoneos 
            -configuration Release 
            archive 
            -archivePath /HoS.xcarchive 
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
      - name: Export unsigned IPA
        script: |
          xcodebuild 
            -exportArchive 
            -archivePath /HoS.xcarchive 
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key><string>development</string>
              <key>signingStyle</key><string>manual</string>
              <key>compileBitcode</key><false/>
              <key>thinning</key><string>&lt;none&gt;</string>
            </dict>
            </plist>') 
            -exportPath /UnsignedIPA
    artifacts:
      - /HoS.xcarchive
      - /UnsignedIPA/*.ipa
