workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      vars:
        XCODE_PROJECT: "HoS.xcodeproj"
        XCODE_SCHEME: "HoS"
      xcode: latest
    scripts:
      - name: Build unsigned iOS app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $PWD/HoS.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export unsigned IPA (xcodebuild)
        script: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>debugging</string>
            <key>signingStyle</key><string>manual</string>
            <key>compileBitcode</key><false/>
            <key>thinning</key><string>&lt;none&gt;</string>
            <key>teamName</key><string>Gaming Mods</string>
          </dict>
          </plist>
          EOF

          # Try exportArchive
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/HoS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/UnsignedIPA || true

      - name: Fallback manual IPA packaging
        script: |
          if [ ! -f $PWD/UnsignedIPA/*.ipa ]; then
            echo "xcodebuild export failed, creating IPA manually..."
            mkdir -p Payload
            cp -r $PWD/HoS.xcarchive/Products/Applications/*.app Payload/
            zip -r HoS.ipa Payload
            mkdir -p UnsignedIPA
            mv HoS.ipa UnsignedIPA/
          fi

    artifacts:
      - HoS.xcarchive
      - UnsignedIPA/*.ipa