workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      vars:
        XCODE_WORKSPACE: "HoS.xcworkspace"
        XCODE_SCHEME: "HoS"
      xcode: latest
    scripts:
      - name: Build unsigned iOS app
        script: |
          xcodebuild 
            -workspace "" 
            -scheme "" 
            -sdk iphoneos 
            -configuration Release 
            archive 
            -archivePath /HoS.xcarchive 
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
    artifacts:
      - /HoS.xcarchive
